# Computer Vision - Week_00 - numpy recap

NumPy stands for Numerical Python. It is a Python library that provides support for large, multi-dimensional arrays and matrices, along with a range of mathematical functions to operate on these arrays.

NumPy is widely used in scientific computing, data analysis, and machine learning. It provides efficient storage and manipulation of large arrays of numerical data, making it easier to work with data in a variety of formats.

# Python common data structures

In [1]:
my_list = [5,2,8]
my_list

[5, 2, 8]

In [2]:
type(my_list)

list

In [3]:
len(my_list)

3

In [4]:
new_set = set(my_list)
new_set

{2, 5, 8}

In [5]:
data = {"my_value" : 35,
 "my_age": 2345,
 "my_school": 324536}

your_data = {"my_value" : 35,
        "my_age": 234546,
        "my_school": 'TULE'}

In [6]:
database = [data, data.copy() ,data.copy(), your_data]

In [7]:
database[0]["my_age"] = 999999

In [8]:
database

[{'my_value': 35, 'my_age': 999999, 'my_school': 324536},
 {'my_value': 35, 'my_age': 2345, 'my_school': 324536},
 {'my_value': 35, 'my_age': 2345, 'my_school': 324536},
 {'my_value': 35, 'my_age': 234546, 'my_school': 'TULE'}]

# 1. Numpy and matrix operation

## INFO: Math entities
Scalars, vectors, matrices, and multidimensional matrices are all mathematical concepts that are used in different fields, including linear algebra, physics, and computer science.

**A scalar** is a single number, such as 1, 2.5, or -3. It has no direction or orientation and can be represented by a single value.

**A vector** is an array of numbers arranged in a specific order. It has magnitude (length) and direction and can be represented graphically as an arrow. In two dimensions, a vector can be represented by a pair of numbers (x, y), while in three dimensions, it can be represented by a triplet of numbers (x, y, z).

**A matrix** is a rectangular array of numbers arranged in rows and columns. It can be represented by a two-dimensional array, where each element of the array represents a single value in the matrix.

**A multidimensional matrix** is a matrix with more than two dimensions. It can be represented as an array of arrays, where each element in the array is itself an array representing a lower-dimensional matrix.

In [ ]:
import numpy as np
import math

## 1.1 Creation of matrix (manual)

In [ ]:
[]

Creating an empty matrix:

In [ ]:
v_empty = np.array([])
v_empty

Row vector / Riadkovy vektor / 1D:  [1 2 3 4]

In [ ]:
v_row = np.array([1, 2, 3, 4])
# v_row = np.array([[1], [2], [3], [4]])
v_row.shape

Matrix (2D): Manually define a matrix with two (1D) row vectors [1,2] and [3,4]:

In [ ]:
A = np.array([[1, 2], [3, 4]])
A

Column vector (manual) definition:

In [ ]:
np.array([[1], [2], [3], [4]])

Getting a column vector by transposing a row vector:

In [ ]:
v_column = np.array([[1, 2, 3, 4]]).T
v_column

## 1.2 Spacial initialization of matrix

The operation linspace returns 10 elements from 0 to 9 (linearly spaced):

In [ ]:
lin_spaced_vector = np.linspace(0, 9, 10)
print(lin_spaced_vector)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Create a (2D) matrix of zeros:

In [ ]:
mat_zeros = np.zeros((3, 3))  # tuple as input param
mat_zeros

Create a (3D) matrix of zeros:

In [ ]:
mat_zeros = np.zeros((3, 3, 3))  # tuple as input param
mat_zeros

Create a matrix of ones with the defined dimensions:

In [ ]:
mat_ones = np.ones((3, 2))
mat_ones

Create a diagonal matrix of ones with the defined dimensions:

In [ ]:
mat_eye = np.eye(6)
mat_eye

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
((mat_eye * (-1) + 1) * 5) + mat_eye * 8

array([[8., 5., 5., 5., 5., 5.],
       [5., 8., 5., 5., 5., 5.],
       [5., 5., 8., 5., 5., 5.],
       [5., 5., 5., 8., 5., 5.],
       [5., 5., 5., 5., 8., 5.],
       [5., 5., 5., 5., 5., 8.]])

Random initialized values in matrix with the defined dimensions (float values from the range 0 to 1):

In [ ]:
mat_rand = np.random.rand(2, 3)
mat_rand

array([[0.90699193, 0.01365439, 0.0476498 ],
       [0.67173383, 0.45191159, 0.76253704]])

## 1.3 Spacial operations

If we want a diagonal matrix with a specific value along the diagonal:

In [ ]:
mat_eye = np.eye(3)*5
mat_eye

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

To find out whether the value at a given position meets a condition:

In [ ]:
mat_eye == 0

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

If we want to also changes zeros:

In [ ]:
mat_eye[mat_eye == 0] = 3
mat_eye

array([[5., 3., 3.],
       [3., 5., 3.],
       [3., 3., 5.]])

In [ ]:
mat_eye[mat_eye > 4 ] = -999
mat_eye

array([[-999.,    3.,    3.],
       [   3., -999.,    3.],
       [   3.,    3., -999.]])

## 1.4 Accessing matrix elements

In [ ]:
vec = np.array([4, 5, 4, 0, 9])
print(vec[0], type(vec[0]))
print(vec[2], type(vec[2]))
print(vec[0:1], type(vec[0:1]))
print(vec[0:2], type(vec[0:2]))
print(vec[0:3], type(vec[0:3]))
print(vec[3:], type(vec[1:]))
print(vec[:3], type(vec[:3]))
print(vec[-1], type(vec[-1]))
print(vec[0:4], type(vec[0:3]))

4 <class 'numpy.int32'>
4 <class 'numpy.int32'>
[4] <class 'numpy.ndarray'>
[4 5] <class 'numpy.ndarray'>
[4 5 4] <class 'numpy.ndarray'>
[0 9] <class 'numpy.ndarray'>
[4 5 4] <class 'numpy.ndarray'>
9 <class 'numpy.int32'>
[4 5 4 0] <class 'numpy.ndarray'>


In [ ]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(mat)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
print(mat[1:3])

[[4 5 6]
 [7 8 9]]


In [ ]:
print("Accessing  element at (2,3):", mat[1][2])
print("Accesing different elements through sequences:")
print("The first line as a row vector:", mat[0][:])
print("The second column as a row vector:", mat[:,1])
print("A submatrix from a certain set:")
print(mat[1:3, 1:3])
print("")
print("A submatrix from a certain index until the end:")
print(mat[1:, 1:])
print("")
print("A submatrix from the beginning to a certain index:")
print(mat[:3, :3])

Accessing  element at (2,3): 6
Accesing different elements through sequences:
The first line as a row vector: [1 2 3]
The second column as a row vector: [ 2  5  8 11]
A submatrix from a certain set:
[[5 6]
 [8 9]]

A submatrix from a certain index until the end:
[[ 5  6]
 [ 8  9]
 [11 12]]

A submatrix from the beginning to a certain index:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Getting the dimensions/shape of a matrix:

In [ ]:
print("Shape of the matrix", mat.shape)
print("Number of rows", mat.shape[0])
print("Number of columns", mat.shape[1])

Shape of the matrix (4, 3)
Number of rows 4
Number of columns 3


## 1.5 Matrix and math operations

In [ ]:
vec_a = np.array([[1, 2, 3, 4]]).T
print(vec_a)

[[1]
 [2]
 [3]
 [4]]


In [ ]:
vec_b = np.array([[2, 4, 6, 8]])
print(vec_b)

[[2 4 6 8]]


In [ ]:
print("Transposing a 1D array does not work:")
test_v = np.array([1, 2, 3, 4])
print(test_v)
print(test_v.T)

Transposing a 1D array does not work:
[1 2 3 4]
[1 2 3 4]


In [ ]:
test_v = np.array([[1, 2, 3, 4]])
print(test_v)
print(test_v.T)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [ ]:
print(2 * vec_a)

In [ ]:
print(vec_a / 2)

In [ ]:
print(vec_a ** 3)

In [ ]:
print(vec_a * vec_b)

In [ ]:
print(vec_a * (vec_a+2))

In [ ]:
print(vec_a / vec_a)

In [ ]:
print(vec_b / vec_a)

In [ ]:
print(vec_a - vec_b)

In [ ]:
print(vec_b - vec_a)

In [ ]:
print(np.log(vec_a))

In [ ]:
print(np.round(np.log(vec_a),2))

 ## 1.6 Matrix scalar operations

In [ ]:
print(np.sum(vec_a))
print(np.mean(vec_a))
print(np.var(vec_a))
print(np.std(vec_a))
print(np.min(vec_a), np.max(vec_a))
print(np.ptp(vec_a))

10
2.5
1.25
1.118033988749895
1 4
3


In [ ]:
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
print("Max of mat along axis 0: ", np.max(mat, 0))
print("Max of mat along axis 1: ", np.max(mat, 1))
print("Mean of mat along axis 0: ", np.mean(mat, 0))
print("Mean of mat along axis 1: ", np.mean(mat, 1))

Max of mat along axis 0:  [10 11 12]
Max of mat along axis 1:  [ 3  6  9 12]
Mean of mat along axis 0:  [5.5 6.5 7.5]
Mean of mat along axis 1:  [ 2.  5.  8. 11.]


Determinant

In [ ]:
matrix = np.random.rand(4,4)
print(matrix)
print(np.linalg.det(matrix))

[[0.20273362 0.36501593 0.22407234 0.46446927]
 [0.28016315 0.6145038  0.06495091 0.04518   ]
 [0.95483398 0.98884852 0.7023     0.89744791]
 [0.10055028 0.05210474 0.93687913 0.11509916]]
0.09906107679768307


Get diagonal from matrix

In [ ]:
print(np.diag(matrix))

[0.20273362 0.6145038  0.7023     0.11509916]


In [ ]:
print(np.diag(matrix,2))

[0.22407234 0.04518   ]


In [ ]:
print(np.diag(matrix,-1))

[0.28016315 0.98884852 0.93687913]


In [ ]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
print(np.repeat(A, 2,axis=0))

[[1 2]
 [1 2]
 [3 4]
 [3 4]]


In [ ]:
np.repeat(A, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [ ]:
print(np.repeat(A, 2,axis=1))

[[1 1 2 2]
 [3 3 4 4]]


In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
np.append(A, A*(-1),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]])

In [ ]:
np.append(A, A*(-1),axis=1)

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])

In [ ]:
matrix

array([[0.20273362, 0.36501593, 0.22407234, 0.46446927],
       [0.28016315, 0.6145038 , 0.06495091, 0.04518   ],
       [0.95483398, 0.98884852, 0.7023    , 0.89744791],
       [0.10055028, 0.05210474, 0.93687913, 0.11509916]])

Changing the shape of a matrix (size must be the same):

In [ ]:
matrix.reshape(2,8)

array([[0.20273362, 0.36501593, 0.22407234, 0.46446927, 0.28016315,
        0.6145038 , 0.06495091, 0.04518   ],
       [0.95483398, 0.98884852, 0.7023    , 0.89744791, 0.10055028,
        0.05210474, 0.93687913, 0.11509916]])

Matrix concatenation (dimensions must match):

In [ ]:
print(vec_a.shape)
print(vec_b.shape)
np.concatenate((vec_a, vec_b.T), 0)

(4, 1)
(1, 4)


array([[1],
       [2],
       [3],
       [4],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
print(vec_a.shape)
print(vec_b.shape)
np.concatenate((vec_a, vec_b.T), 1)

(4, 1)
(1, 4)


array([[1, 2],
       [2, 4],
       [3, 6],
       [4, 8]])

In [ ]:
print(vec_a.shape)
print(vec_b.shape)
np.array((vec_a, vec_b))

(4, 1)
(1, 4)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

##**Autonomous work:**

1. Create a 640x480 random matrix with decimal numbers from the interval 0-1. Convert it to a matrix that has 480 rows and 640 columns.

2. Convert the matrix to a matrix of integers from the interval 0-255, so that 0 corresponds to 0 and 1 to 255. Set all elements of the matrix that are less than 50 to zero.

3. Study how it is done and normalize the matrix to unit length (matrix norm = 1).

 ## 1.7 Matrix vector operations

When working with matrices, you often have to calculate scalar and vector products. You must understand the differences between various operations and their notation.

In [3]:
mat_a = np.array([[1, 2, 3]])
mat_b = np.array([[4, 5, 6]])

NameError: name 'np' is not defined

In [4]:
print(mat_a * mat_b)    # elementwise
print(mat_a.T * mat_b)  # vector product
print(mat_a * mat_b.T)  # vector product
print(mat_a.T @ mat_b)  # dot product

NameError: name 'mat_a' is not defined

# Linear algebra:

In [ ]:
V, D = np.linalg.eig(np.random.rand(3, 3))
print("Eigen values: \n",V,"\n Eigen matrix\n",D)

Eigen values: 
 [ 1.88000228 -0.12805865  0.03114857] 
 Eigen matrix
 [[ 6.13741036e-01  2.80228193e-01  9.86655983e-05]
 [ 5.04367147e-01 -7.30445249e-01 -6.16606336e-01]
 [ 6.07400792e-01  6.22833765e-01  7.87271628e-01]]


In [ ]:
U, S, V = np.linalg.svd(np.random.rand(3, 3))
print("SVD single value decomposition: \n", U,"\n Eigen matrix\n",S,"\n Eigen matrix\n",V) # a = U * S * V'

SVD single value decomposition: 
 [[-0.56651278 -0.13008496  0.81372058]
 [-0.62049886  0.71712691 -0.31734863]
 [-0.54225864 -0.68469475 -0.48697913]] 
 Eigen matrix
 [1.75272884 0.72635243 0.29254492] 
 Eigen matrix
 [[-0.70971988 -0.49451384 -0.50175069]
 [ 0.03209732  0.68878656 -0.7242533 ]
 [-0.70375241  0.53012182  0.47297294]]
