In [8]:
# trenovanie a ukladanie modelov
import yfinance as yf
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
import os

# Stock tickers
tickers = [
    'NVDA', 'TSLA', 'INTC', 'F', 'AAPL', 'MSFT', 'AMZN',
    'GOOGL', 'META', 'BRK-B', 'JPM', 'V', 'JNJ', 'WMT',
    'PG', 'XOM', 'NKE', 'CVS', 'PM', 'NEM'
]

start_date = '2020-04-01'
end_date = '2025-04-01'
time_steps = 10

model_dir = "models"
os.makedirs(model_dir, exist_ok=True)

def create_lstm_data(data, time_steps=1):
    x, y = [], []
    for i in range(len(data) - time_steps):
        x.append(data[i:(i + time_steps), 0])
        y.append(data[i + time_steps, 0])
    return np.array(x), np.array(y)

for ticker in tickers:
    print(f"\nProcessing {ticker}...")
    data = yf.download(ticker, start=start_date, end=end_date)

    if data.empty:
        print(f"No data for {ticker}. Skipping.")
        continue

    close_prices = data['Close'].values.reshape(-1, 1)
    scaler = MinMaxScaler(feature_range=(0, 1))
    close_prices_scaled = scaler.fit_transform(close_prices)

    x, y = create_lstm_data(close_prices_scaled, time_steps)
    x = np.reshape(x, (x.shape[0], x.shape[1], 1))

    model = Sequential()
    model.add(LSTM(units=50, return_sequences=True, input_shape=(x.shape[1], 1)))
    model.add(LSTM(units=50))
    model.add(Dense(units=1))
    model.compile(optimizer='adam', loss='mean_squared_error')
    model.fit(x, y, epochs=50, batch_size=32, verbose=0)

    # ✅ Save model
    model.save(f"{model_dir}/{ticker}.h5")

    # ✅ Save scaler
    import joblib
    joblib.dump(scaler, f"{model_dir}/{ticker}_scaler.gz")

    print(f"Saved model and scaler for {ticker}")


Processing NVDA...


[*********************100%***********************]  1 of 1 completed
C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for NVDA

Processing TSLA...


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for TSLA

Processing INTC...


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for INTC

Processing F...


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for F

Processing AAPL...


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for AAPL

Processing MSFT...


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for MSFT

Processing AMZN...


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for AMZN

Processing GOOGL...


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for GOOGL

Processing META...


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for META

Processing BRK-B...


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for BRK-B

Processing JPM...


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for JPM

Processing V...


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for V

Processing JNJ...


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for JNJ

Processing WMT...


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for WMT

Processing PG...


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for PG

Processing XOM...


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for XOM

Processing NKE...


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for NKE

Processing CVS...


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for CVS

Processing PM...


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
[*********************100%***********************]  1 of 1 completed


Saved model and scaler for PM

Processing NEM...
Saved model and scaler for NEM


C:\Users\Lenovo\.conda\envs\newConda\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [14]:
# lokalny test modelu
from tensorflow.keras.models import load_model

ticker = 'TSLA'

def predict_next_days(ticker, days=10, time_steps=10, end_date='2025-04-05'):
    model = load_model(f"models/{ticker}.h5")
    scaler = joblib.load(f"models/{ticker}_scaler.gz")
    start_date = '2020-04-01'
    data = yf.download(ticker, start=start_date, end=end_date)

    close_prices = data['Close'].values.reshape(-1, 1)
    close_prices_scaled = scaler.transform(close_prices)

    last_data = close_prices_scaled[-time_steps:]
    last_data = np.reshape(last_data, (1, time_steps, 1))

    future_predictions = []
    for _ in range(days):
        pred = model.predict(last_data, verbose=0)
        future_predictions.append(pred[0][0])
        last_data = np.append(last_data[:, 1:, :], pred.reshape(1, 1, 1), axis=1)

    future_predictions = scaler.inverse_transform(np.array(future_predictions).reshape(-1, 1))
    return future_predictions

print(predict_next_days(ticker, 5, 10, '2025-04-05'))


[*********************100%***********************]  1 of 1 completed


[[254.91391]
 [250.02374]
 [247.0321 ]
 [244.5758 ]
 [242.4207 ]]


In [36]:
# prevod .h5 modelov na tensorflow, vhodne pre vertex ai

import tensorflow as tf

for ticker in tickers:
    model = tf.keras.models.load_model(f"models/{ticker}.h5")
    model.save(f"models/{ticker}c", save_format='tf')


INFO:tensorflow:Assets written to: models/NVDAc\assets


INFO:tensorflow:Assets written to: models/NVDAc\assets


INFO:tensorflow:Assets written to: models/TSLAc\assets


INFO:tensorflow:Assets written to: models/TSLAc\assets


INFO:tensorflow:Assets written to: models/INTCc\assets


INFO:tensorflow:Assets written to: models/INTCc\assets


INFO:tensorflow:Assets written to: models/Fc\assets


INFO:tensorflow:Assets written to: models/Fc\assets


INFO:tensorflow:Assets written to: models/AAPLc\assets


INFO:tensorflow:Assets written to: models/AAPLc\assets


INFO:tensorflow:Assets written to: models/MSFTc\assets


INFO:tensorflow:Assets written to: models/MSFTc\assets


INFO:tensorflow:Assets written to: models/AMZNc\assets


INFO:tensorflow:Assets written to: models/AMZNc\assets


INFO:tensorflow:Assets written to: models/GOOGLc\assets


INFO:tensorflow:Assets written to: models/GOOGLc\assets


INFO:tensorflow:Assets written to: models/METAc\assets


INFO:tensorflow:Assets written to: models/METAc\assets


INFO:tensorflow:Assets written to: models/BRK-Bc\assets


INFO:tensorflow:Assets written to: models/BRK-Bc\assets


INFO:tensorflow:Assets written to: models/JPMc\assets


INFO:tensorflow:Assets written to: models/JPMc\assets


INFO:tensorflow:Assets written to: models/Vc\assets


INFO:tensorflow:Assets written to: models/Vc\assets


INFO:tensorflow:Assets written to: models/JNJc\assets


INFO:tensorflow:Assets written to: models/JNJc\assets


INFO:tensorflow:Assets written to: models/WMTc\assets


INFO:tensorflow:Assets written to: models/WMTc\assets


INFO:tensorflow:Assets written to: models/PGc\assets


INFO:tensorflow:Assets written to: models/PGc\assets


INFO:tensorflow:Assets written to: models/XOMc\assets


INFO:tensorflow:Assets written to: models/XOMc\assets


INFO:tensorflow:Assets written to: models/NKEc\assets


INFO:tensorflow:Assets written to: models/NKEc\assets


INFO:tensorflow:Assets written to: models/CVSc\assets


INFO:tensorflow:Assets written to: models/CVSc\assets


INFO:tensorflow:Assets written to: models/PMc\assets


INFO:tensorflow:Assets written to: models/PMc\assets


INFO:tensorflow:Assets written to: models/NEMc\assets


INFO:tensorflow:Assets written to: models/NEMc\assets


In [1]:
# inicializacia credentials pre vertex ai a storage

import os
from google.cloud import aiplatform

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "prefab-shape-455916-i7-be937e48d8e1.json"

aiplatform.init(
    project="4204132242382913536",
    location="europe-central2"
)

endpoint = aiplatform.Endpoint("4204132242382913536")

import google.auth
creds, project = google.auth.default()
print("Authenticated project:", project)
print("Credentials type:", type(creds))

Authenticated project: prefab-shape-455916-i7
Credentials type: <class 'google.oauth2.service_account.Credentials'>


In [6]:
# predickia modelu z endpointu na vertex ai

from google.cloud import aiplatform
from google.cloud import storage
import numpy as np
import yfinance as yf
import joblib
import io

def load_scaler_from_gcs(bucket_name, blob_name):
    storage_client = storage.Client()
    bucket = storage_client.bucket(bucket_name)
    blob = bucket.blob(blob_name)
    scaler_bytes = blob.download_as_bytes()
    scaler = joblib.load(io.BytesIO(scaler_bytes))
    return scaler

def predict_next_days_vertexai(
        ticker, endpoint_id, project, location, days=5, time_steps=10, end_date='2025-04-05'
):
    # Initialize Vertex AI
    aiplatform.init(project=project, location=location)
    endpoint = aiplatform.Endpoint(endpoint_id)

    # Load scaler from GCS
    scaler = load_scaler_from_gcs("stock-prediction-zct", f"{ticker}_scaler.gz")

    # Download stock data
    start_date = '2020-04-01'
    data = yf.download(ticker, start=start_date, end=end_date)
    close_prices = data['Close'].values.reshape(-1, 1)
    close_prices_scaled = scaler.transform(close_prices)

    # Get the last time_steps data, reshape to (1, time_steps, 1)
    last_data = close_prices_scaled[-time_steps:]
    print(last_data)
    last_data = np.reshape(last_data, (1, time_steps, 1))
    print(last_data)

    future_predictions = []
    for _ in range(days):
        response = endpoint.predict(instances=last_data.tolist())
        pred = response.predictions[0][0]
        future_predictions.append(pred)

        last_data = np.append(last_data[:, 1:, :], np.array(pred).reshape(1, 1, 1), axis=1)

    print(future_predictions)
    future_predictions = scaler.inverse_transform(np.array(future_predictions).reshape(-1, 1))
    print(future_predictions)
    return future_predictions


preds = predict_next_days_vertexai(
    ticker="AAPL",
    endpoint_id="4204132242382913536",
    project="prefab-shape-455916-i7",
    location="europe-central2",
    days=20
)

#AAPL - 4204132242382913536
#NVDA - 8849595258015580160

print(preds)

[*********************100%***********************]  1 of 1 completed


[[0.81023027]
 [0.8253098 ]
 [0.81422485]
 [0.82580915]
 [0.79609945]
 [0.81722081]
 [0.82251361]
 [0.82600885]
 [0.72264928]
 [0.64869975]]
[[[0.81023027]
  [0.8253098 ]
  [0.81422485]
  [0.82580915]
  [0.79609945]
  [0.81722081]
  [0.82251361]
  [0.82600885]
  [0.72264928]
  [0.64869975]]]
[0.74511826, 0.722068, 0.706082523, 0.693850577, 0.685101, 0.676949263, 0.671317875, 0.667188048, 0.664371848, 0.65790391, 0.648788, 0.644508779, 0.639706731, 0.634662151, 0.629504204, 0.624349773, 0.619193196, 0.61411792, 0.609173, 0.604409337]
[[207.68990335]
 [203.07358846]
 [199.87214972]
 [197.42243703]
 [195.67014432]
 [194.03758205]
 [192.90977437]
 [192.08268687]
 [191.51868169]
 [190.22333672]
 [188.39767787]
 [187.54067099]
 [186.57895664]
 [185.56867   ]
 [184.53567916]
 [183.50339247]
 [182.470676  ]
 [181.45424182]
 [180.46391426]
 [179.50988734]]
[[207.68990335]
 [203.07358846]
 [199.87214972]
 [197.42243703]
 [195.67014432]
 [194.03758205]
 [192.90977437]
 [192.08268687]
 [191.518681